#!/bin/bash -ex

VERSION="2.0.2"
URL="https://github.com/Pligg/pligg-cms/releases/download/${VERSION}/${VERSION}.zip"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY "$URL" -o /usr/local/src/pligg.zip

