#!/bin/bash -ex

VERSION="1.2.2"
URL="http://sourceforge.net/projects/pligg/files/Pligg%20CMS/Pligg%20CMS%20${VERSION}.zip"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY "$URL" -o /usr/local/src/pligg.zip

