#!/bin/sh -ex

DB_NAME=pligg
DB_USER=pligg
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/pligg

# unpack and set permissions
unzip $SRC/pligg.zip -d $SRC
rm $SRC/pligg.zip
mv $SRC/pligg* $WEBROOT

chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/languages
chown -R www-data:www-data $WEBROOT/templates
chown -R www-data:www-data $WEBROOT/admin/backup
chown -R www-data:www-data $WEBROOT/avatars/user_uploaded
chown -R www-data:www-data $WEBROOT/avatars/groups_uploaded

# create required files from defaults, and set permissions
mv $WEBROOT/settings.php.default $WEBROOT/settings.php
mv $WEBROOT/libs/dbconnect.php.default $WEBROOT/libs/dbconnect.php
mv $WEBROOT/languages/lang_english.conf.default $WEBROOT/languages/lang_english.conf

chown www-data:www-data $WEBROOT/settings.php
chown www-data:www-data $WEBROOT/libs/dbconnect.php

# configure apache
a2dissite default
a2ensite pligg
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
DBCON="dbname=$DB_NAME&dbuser=$DB_USER&dbpass=$DB_PASS&dbhost=localhost&tableprefix="

URL="http://127.0.0.1/install/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

# $CURL "${URL}"
# $CURL "${URL}?language=local"
$CURL "${URL}?step=1&language=english"
$CURL "${URL}" --data "Submit=Next+Step&language=english&step=2"
$CURL "${URL}" --data "${DBCON}&Submit=Check+Settings&language=english&step=3"
$CURL "${URL}" --data "${DBCON}&Submit=Next+Step&language=english&step=4"
$CURL "${URL}" --data "adminlogin=$ADMIN_NAME&adminpassword=$ADMIN_PASS&adminpassword2=$ADMIN_PASS&adminemail=$EMAIL&Submit=Create+Admin+Account&language=english&step=5"

rm -f /tmp/cookie
rm -rf $WEBROOT/install

# create welcome story
TITLE="Welcome to TurnKey Pligg"
CONTENT='Lets get you started... Log into the <a href=\"/admin\">admin area</a> as <b>admin</b> and customize your your site. For more information check out the <a href=\"http://www.turnkeylinux.org/pligg\">release notes</a> and the official <a href=\"http://forums.pligg.com\">Pligg forums</a>.'
DATE="2012-01-01 01:00:00"
$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO links VALUES (2, 1, 'published', '261185', 1, 0, 0, 1.00, '$DATE', '$DATE', '$DATE', 1, 1, 'http://www.turnkeylinux.org/pligg', '$TITLE', '$TITLE', 'turnkey-pligg', '$CONTENT', '$CONTENT', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 'queued', 0);"
$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE totals SET total=1 WHERE name=\"published\";"

# set base url to be dynamic
CONF=$WEBROOT/settings.php
sed -i "s|base_url.*|base_url = \"http://\".\$_SERVER[\"HTTP_HOST\"];|" $CONF

# set site name
CONF=$WEBROOT/languages/lang_english.conf
sed -i "s|Visual_Name.*|Visual_Name = \"TurnKey Pligg\"|" $CONF

# enable htaccess
mv $WEBROOT/htaccess.default $WEBROOT/.htaccess

# secure sensitive files
chmod 640 $WEBROOT/settings.php
chmod 640 $WEBROOT/libs/dbconnect.php

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

