#!/bin/sh -ex

DB_NAME=pligg
DB_USER=pligg
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/pligg

# unpack and set permissions
unzip $SRC/Pligg_CMS_*.zip -d $(dirname $WEBROOT)
rm $(dirname $WEBROOT)/Pligg*
rm $SRC/Pligg_CMS_*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/languages
chown -R www-data:www-data $WEBROOT/templates
chown -R www-data:www-data $WEBROOT/admin/backup
chown -R www-data:www-data $WEBROOT/avatars/user_uploaded
chown -R www-data:www-data $WEBROOT/avatars/groups_uploaded

# create required files from defaults, and set permissions
mv $WEBROOT/settings.php.default $WEBROOT/settings.php
mv $WEBROOT/libs/dbconnect.php.default $WEBROOT/libs/dbconnect.php
mv $WEBROOT/languages/lang_english.conf.default $WEBROOT/languages/lang_english.conf
mv $WEBROOT/bannedips.txt.default $WEBROOT/bannedips.txt
mv $WEBROOT/approvedips.txt.default $WEBROOT/approvedips.txt
mv $WEBROOT/local-antispam.txt.default $WEBROOT/local-antispam.txt

chown www-data:www-data $WEBROOT/settings.php
chown www-data:www-data $WEBROOT/libs/dbconnect.php
chown www-data:www-data $WEBROOT/bannedips.txt
chown www-data:www-data $WEBROOT/approvedips.txt
chown www-data:www-data $WEBROOT/local-antispam.txt

# configure apache
a2dissite default
a2ensite pligg
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
DBCON="dbname=$DB_NAME&dbuser=$DB_USER&dbpass=$DB_PASS&dbhost=localhost&tableprefix="

URL="http://127.0.0.1/install/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL "${URL}"
$CURL "${URL}?language=local"
$CURL "${URL}?step=1"
$CURL "${URL}" --data "Submit=Next&language=&step=2"
$CURL "${URL}" --data "${DBCON}&Submit=Check+Settings&language=&step=3"
$CURL "${URL}" --data "${DBCON}&Submit=Next&language=&step=4"
$CURL "${URL}" --data "godlogin=$ADMIN_NAME&godpassword=$ADMIN_PASS&godpassword2=$ADMIN_PASS&godemail=$EMAIL&Submit=Create+Admin+Account&language=&step=5"

rm -f /tmp/cookie
rm -rf $WEBROOT/install

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

