#!/bin/bash -e
# regenerate pligg mysql password

. /etc/default/inithooks

CONF=/var/www/pligg/libs/dbconnect.php
PASSWORD=$(mcookie)
sed -i "s|PASSWORD.*|PASSWORD\", '$PASSWORD');|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=pligg --pass="$PASSWORD"

