#!/bin/bash -e
# regenerate kliqqi mysql password

. /etc/default/inithooks

CONF=/var/www/kliqqi/libs/dbconnect.php
PASSWORD=$(mcookie)
sed -i "s|PASSWORD.*|PASSWORD\", '$PASSWORD');|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=kliqqi --pass="$PASSWORD"

